@extends('layouts.app')

@section('title', 'End-of-Term Academic Risk Report - AcadAlert')

@section('page_title', 'End-of-Term Academic Risk Report')

@section('page_actions')
    <div class="d-flex flex-wrap gap-2">
        <a href="{{ $pdfRoute }}" class="btn btn-sm btn-danger">
            <i class="fas fa-file-pdf me-1"></i> Download PDF
        </a>

        @if(!empty($verifyRoute))
            <button type="button" class="btn btn-sm btn-outline-info" id="verifyBtn">
                <i class="fas fa-fingerprint me-1"></i> Verify Integrity
            </button>
        @endif

        <a href="{{ $backRoute }}" class="btn btn-sm btn-outline-secondary">
            <i class="fas fa-arrow-left me-1"></i> {{ $backLabel ?? 'Back' }}
        </a>
    </div>
@endsection

@section('content')
@php
    $snapshotMeta = $snapshot['meta'] ?? [];
    $department = $snapshotMeta['department'] ?? [];
    $totals = $totals ?? [];
    $comparison = $comparison ?? [];
    $counts = $snapshot['counts_by_level'] ?? ['High' => 0, 'Moderate' => 0, 'Low' => 0];
    $percentages = $snapshot['percentages_by_level'] ?? ['High' => 0, 'Moderate' => 0, 'Low' => 0];
    $sharedRoles = json_decode((string) ($report->shared_roles ?? ''), true) ?: [];
@endphp

{{-- /* CHANGED: mirror the PDF's centered university and AcadAlert header in the on-screen report. */ --}}
<style>
    /* CHANGED: keep the preview header centered, proportional, and separated from content by a black rule. */
    .end-of-term-report-header {
        color: #000;
        background: #fff;
        margin: 0 0 1.5rem;
    }

    .end-of-term-report-header__row {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 14px;
        padding: 0.5rem 0 0.75rem;
    }

    .end-of-term-report-header__udd {
        width: 72px;
        height: 72px;
        object-fit: contain;
        flex: 0 0 auto;
    }

    .end-of-term-report-header__title {
        margin: 0;
        color: #000;
        font-family: Arial, Helvetica, sans-serif;
        font-size: 22px;
        font-weight: 700;
        line-height: 1.1;
        white-space: nowrap;
    }

    .end-of-term-report-header__acadalert {
        width: 70px;
        height: auto;
        flex: 0 0 auto;
    }

    .end-of-term-report-header__rule {
        height: 2px;
        border: 0;
        margin: 0;
        background: #000;
        opacity: 1;
    }

    @media (max-width: 600px) {
        .end-of-term-report-header__row {
            gap: 8px;
        }

        .end-of-term-report-header__udd {
            width: 54px;
            height: 54px;
        }

        .end-of-term-report-header__title {
            font-size: clamp(12px, 3.6vw, 18px);
        }

        .end-of-term-report-header__acadalert {
            width: 54px;
        }
    }
</style>
<div class="end-of-term-report-header">
    <div class="end-of-term-report-header__row">
        <img class="end-of-term-report-header__udd" src="{{ asset('images/logo/udd-logo.png') }}" alt="Universidad de Dagupan logo">
        <h1 class="end-of-term-report-header__title">UNIVERSIDAD DE DAGUPAN</h1>
        <img class="end-of-term-report-header__acadalert" src="{{ asset('images/logo/acadalert_logo.png') }}" alt="AcadAlert logo">
    </div>
    <hr class="end-of-term-report-header__rule">
</div>

<div class="card mb-4">
    <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center flex-wrap gap-2">
        <div>
            <i class="fas fa-file-alt me-2"></i>
            <span class="fw-bold">{{ $department['code'] ?? '' }} - {{ $department['name'] ?? '' }}</span>
        </div>
        <div class="d-flex flex-wrap gap-2">
            <span class="badge bg-light text-dark">
                {{ $snapshotMeta['school_year'] ?? '' }} &middot; {{ ($snapshotMeta['semester'] ?? '1st') === '2nd' ? 'Second' : 'First' }} Semester
            </span>
            <span class="badge bg-light text-dark">
                {{ $snapshotMeta['grading_period'] ?? '' }} (period {{ $periodNumber }} of {{ $periodCount }})
            </span>
            @if($report && $report->is_shared)
                <span class="badge bg-success"><i class="fas fa-share-alt me-1"></i> Shared</span>
            @elseif($report)
                <span class="badge bg-secondary"><i class="fas fa-lock me-1"></i> Not shared</span>
            @endif
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-6">
                <dl class="row mb-0 small">
                    <dt class="col-5">Generated</dt>
                    <dd class="col-7">{{ $snapshotMeta['generated_at'] ?? 'n/a' }} UTC</dd>
                    <dt class="col-5">Generated By</dt>
                    <dd class="col-7">{{ $generatedByName }}</dd>
                    <dt class="col-5">Previous Period</dt>
                    <dd class="col-7">{{ $comparison['previous_period'] ?? 'None (baseline period)' }}</dd>
                </dl>
            </div>
            <div class="col-md-6">
                <dl class="row mb-0 small">
                    <dt class="col-5">Computation</dt>
                    <dd class="col-7"><span class="badge bg-info text-dark">Deterministic rule-based</span></dd>
                    <dt class="col-5">Generative AI Used</dt>
                    <dd class="col-7">
                        <span class="badge bg-success">NO</span>
                        <span class="text-muted ms-1">0 external service calls</span>
                    </dd>
                    <dt class="col-5">Formula Version</dt>
                    <dd class="col-7">v{{ $formulaVersion }}</dd>
                    <dt class="col-5">Snapshot SHA-256</dt>
                    <dd class="col-7"><code class="small text-break">{{ $digest }}</code></dd>
                </dl>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="stat-card primary">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <div class="stat-label">Students Monitored</div>
                    <div class="stat-number">{{ number_format((int) ($totals['monitored'] ?? 0)) }}</div>
                    <small class="text-muted">
                        of {{ number_format((int) ($totals['active_students'] ?? 0)) }} active
                        ({{ number_format((float) ($totals['coverage_percentage'] ?? 0), 2) }}%)
                    </small>
                </div>
                <div class="stat-icon"><i class="fas fa-users"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="stat-card danger">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <div class="stat-label">High Risk</div>
                    <div class="stat-number">{{ number_format((int) $counts['High']) }}</div>
                    <small class="text-muted">{{ number_format((float) $percentages['High'], 2) }}% of monitored</small>
                </div>
                <div class="stat-icon"><i class="fas fa-exclamation-triangle"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="stat-card warning">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <div class="stat-label">Moderate Risk</div>
                    <div class="stat-number">{{ number_format((int) $counts['Moderate']) }}</div>
                    <small class="text-muted">{{ number_format((float) $percentages['Moderate'], 2) }}% of monitored</small>
                </div>
                <div class="stat-icon"><i class="fas fa-minus-circle"></i></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="stat-card success">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <div class="stat-label">Low Risk</div>
                    <div class="stat-number">{{ number_format((int) $counts['Low']) }}</div>
                    <small class="text-muted">{{ number_format((float) $percentages['Low'], 2) }}% of monitored</small>
                </div>
                <div class="stat-icon"><i class="fas fa-check-circle"></i></div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-6 mb-4">
        <div class="card h-100">
            <div class="card-header">
                <i class="fas fa-table text-primary me-2"></i> Risk Classification &amp; Percentage Distribution
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover align-middle mb-0">
                        <thead>
                            <tr>
                                <th>Risk Category</th>
                                <th class="text-end">Students</th>
                                <th class="text-end">Percentage</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($distribution as $row)
                                <tr>
                                    <td>
                                        <span class="badge {{ $row['risk_level'] === 'High' ? 'bg-danger' : ($row['risk_level'] === 'Moderate' ? 'bg-warning text-dark' : 'bg-success') }}">
                                            {{ $row['risk_level'] }}
                                        </span>
                                    </td>
                                    <td class="text-end">{{ number_format((int) $row['count']) }}</td>
                                    <td class="text-end">{{ number_format((float) $row['percentage'], 2) }}%</td>
                                </tr>
                            @endforeach
                        </tbody>
                        <tfoot>
                            <tr class="fw-bold">
                                <td>Total monitored</td>
                                <td class="text-end">{{ number_format((int) ($totals['monitored'] ?? 0)) }}</td>
                                <td class="text-end">100.00%</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <p class="text-muted small mt-3 mb-0">
                    <i class="fas fa-info-circle me-1"></i>
                    Percentages are apportioned with the largest-remainder method, so the three categories
                    always total exactly 100.00%.
                </p>
            </div>
        </div>
    </div>

    <div class="col-xl-6 mb-4">
        <div class="card h-100">
            <div class="card-header">
                <i class="fas fa-chart-bar text-primary me-2"></i>
                Risk Distribution
                @if(!empty($chart['previousPeriod']))
                    <span class="text-muted small ms-1">({{ $snapshotMeta['grading_period'] ?? '' }} vs {{ $chart['previousPeriod'] }})</span>
                @endif
            </div>
            <div class="card-body">
                <div class="chart-container" style="height: 260px;">
                    <canvas id="eotDistributionChart" data-chart='@json($chart)'></canvas>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-balance-scale text-primary me-2"></i>
        Comparative Summary vs Previous Grading Period
    </div>
    <div class="card-body">
        @if(!empty($comparison['available']))
            <div class="alert alert-info">
                <i class="fas fa-chart-line me-2"></i>{{ $comparison['headline'] ?? '' }}
            </div>

            <div class="table-responsive">
                <table class="table table-hover align-middle">
                    <thead>
                        <tr>
                            <th>Risk Category</th>
                            <th class="text-end">{{ $snapshotMeta['grading_period'] ?? 'Current' }} (students)</th>
                            <th class="text-end">%</th>
                            <th class="text-end">{{ $comparison['previous_period'] }} (students)</th>
                            <th class="text-end">%</th>
                            <th class="text-end">Change</th>
                            <th class="text-end">&Delta; percentage points</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(['High', 'Moderate', 'Low'] as $level)
                            @php
                                $delta = (int) ($comparison['count_delta'][$level] ?? 0);
                                $pp = (float) ($comparison['percentage_point_delta'][$level] ?? 0);
                                $deltaClass = $delta === 0
                                    ? 'text-muted'
                                    : (($level === 'High') === ($delta > 0) ? 'text-danger fw-bold' : 'text-success fw-bold');
                            @endphp
                            <tr>
                                <td>
                                    <span class="badge {{ $level === 'High' ? 'bg-danger' : ($level === 'Moderate' ? 'bg-warning text-dark' : 'bg-success') }}">
                                        {{ $level }}
                                    </span>
                                </td>
                                <td class="text-end">{{ number_format((int) $counts[$level]) }}</td>
                                <td class="text-end">{{ number_format((float) $percentages[$level], 2) }}%</td>
                                <td class="text-end">{{ number_format((int) ($comparison['previous_counts'][$level] ?? 0)) }}</td>
                                <td class="text-end">{{ number_format((float) ($comparison['previous_percentages'][$level] ?? 0), 2) }}%</td>
                                <td class="text-end {{ $deltaClass }}">{{ $delta >= 0 ? '+' : '' }}{{ $delta }}</td>
                                <td class="text-end {{ $deltaClass }}">{{ $pp >= 0 ? '+' : '' }}{{ number_format($pp, 2) }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr class="fw-bold">
                            <td>Students monitored</td>
                            <td class="text-end">{{ number_format((int) ($totals['monitored'] ?? 0)) }}</td>
                            <td class="text-end">100.00%</td>
                            <td class="text-end">{{ number_format((int) ($comparison['previous_total'] ?? 0)) }}</td>
                            <td class="text-end">100.00%</td>
                            <td class="text-end">{{ (int) ($comparison['total_delta'] ?? 0) >= 0 ? '+' : '' }}{{ (int) ($comparison['total_delta'] ?? 0) }}</td>
                            <td class="text-end">&mdash;</td>
                        </tr>
                    </tfoot>
                </table>
            </div>

            <div class="row mt-3">
                <div class="col-lg-5">
                    <h6 class="fw-bold">Per-student movement</h6>
                    @php $movement = $comparison['transitions'] ?? []; @endphp
                    <table class="table table-sm table-bordered mb-0">
                        <tbody>
                            <tr>
                                <td><i class="fas fa-arrow-down text-success me-2"></i>Improved (less severe category)</td>
                                <td class="text-end fw-bold">{{ number_format((int) ($movement['improved'] ?? 0)) }}</td>
                            </tr>
                            <tr>
                                <td><i class="fas fa-arrow-up text-danger me-2"></i>Worsened (more severe category)</td>
                                <td class="text-end fw-bold">{{ number_format((int) ($movement['worsened'] ?? 0)) }}</td>
                            </tr>
                            <tr>
                                <td><i class="fas fa-equals text-muted me-2"></i>Held classification</td>
                                <td class="text-end fw-bold">{{ number_format((int) ($movement['stable'] ?? 0)) }}</td>
                            </tr>
                            <tr>
                                <td><i class="fas fa-user-plus text-info me-2"></i>Newly monitored</td>
                                <td class="text-end fw-bold">{{ number_format((int) ($movement['newly_monitored'] ?? 0)) }}</td>
                            </tr>
                            <tr>
                                <td><i class="fas fa-user-minus text-secondary me-2"></i>No longer monitored</td>
                                <td class="text-end fw-bold">{{ number_format((int) ($movement['no_longer_monitored'] ?? 0)) }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-lg-7">
                    <h6 class="fw-bold">Narrative summary</h6>
                    <ul class="small mb-0">
                        @foreach(($comparison['lines'] ?? []) as $line)
                            <li>{{ $line }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @else
            <div class="alert alert-secondary mb-0">
                <i class="fas fa-flag me-2"></i>{{ $comparison['headline'] ?? 'No previous period available.' }}
                <ul class="small mb-0 mt-2">
                    @foreach(($comparison['lines'] ?? []) as $line)
                        <li>{{ $line }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
    </div>
</div>

<div class="row">
    <div class="col-xl-7 mb-4">
        <div class="card h-100">
            <div class="card-header">
                <i class="fas fa-sitemap text-primary me-2"></i> Program Breakdown
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover table-sm align-middle mb-0">
                        <thead>
                            <tr>
                                <th>Code</th>
                                <th>Program</th>
                                <th class="text-end">Monitored</th>
                                <th class="text-end">High</th>
                                <th class="text-end">Moderate</th>
                                <th class="text-end">Low</th>
                                <th class="text-end">High %</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($programs as $program)
                                <tr>
                                    <td class="fw-bold">{{ $program['program_code'] }}</td>
                                    <td>{{ $program['program_name'] }}</td>
                                    <td class="text-end">{{ number_format((int) $program['monitored']) }}</td>
                                    <td class="text-end">{{ number_format((int) $program['counts']['High']) }}</td>
                                    <td class="text-end">{{ number_format((int) $program['counts']['Moderate']) }}</td>
                                    <td class="text-end">{{ number_format((int) $program['counts']['Low']) }}</td>
                                    <td class="text-end">{{ number_format((float) $program['percentages']['High'], 2) }}%</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7" class="text-center text-muted py-3">No program data for this period.</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-5 mb-4">
        <div class="card h-100">
            <div class="card-header">
                <i class="fas fa-calculator text-primary me-2"></i> Risk Score Statistics
            </div>
            <div class="card-body">
                <table class="table table-sm mb-0">
                    <tbody>
                        <tr>
                            <td>Students scored</td>
                            <td class="text-end fw-bold">{{ number_format((int) ($scoreStatistics['count'] ?? 0)) }}</td>
                        </tr>
                        <tr>
                            <td>Average risk score</td>
                            <td class="text-end fw-bold">{{ $scoreStatistics['average'] === null ? 'n/a' : number_format((float) $scoreStatistics['average'], 1) }}</td>
                        </tr>
                        <tr>
                            <td>Median risk score</td>
                            <td class="text-end fw-bold">{{ $scoreStatistics['median'] === null ? 'n/a' : number_format((float) $scoreStatistics['median'], 1) }}</td>
                        </tr>
                        <tr>
                            <td>Lowest risk score</td>
                            <td class="text-end fw-bold">{{ $scoreStatistics['minimum'] === null ? 'n/a' : number_format((int) $scoreStatistics['minimum']) }}</td>
                        </tr>
                        <tr>
                            <td>Highest risk score</td>
                            <td class="text-end fw-bold">{{ $scoreStatistics['maximum'] === null ? 'n/a' : number_format((int) $scoreStatistics['maximum']) }}</td>
                        </tr>
                        <tr>
                            <td>Active students without a score</td>
                            <td class="text-end fw-bold">{{ number_format((int) ($totals['without_score'] ?? 0)) }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@php $insights = $insights ?? []; @endphp

@if(!empty($insights))
    @php
        $insightWarning = $insights['warning'] ?? null;
        $intervention = $insights['intervention'] ?? [];
    @endphp

    @if(is_array($insightWarning))
        <div class="alert alert-danger d-flex align-items-start">
            <i class="fas fa-triangle-exclamation fa-2x me-3"></i>
            <div>
                <h6 class="fw-bold mb-1">Configuration warning: {{ $insightWarning['percentage'] }} High Risk</h6>
                <p class="mb-2 small">
                    High risk accounts for {{ $insightWarning['percentage'] }} of monitored students
                    ({{ $insightWarning['high'] }} of {{ $insightWarning['monitored'] }}). The figures in
                    this report are correct — a rate this high normally means the configured risk bands
                    are not discriminating.
                </p>
                <p class="mb-0 small">
                    <strong>Active bands:</strong> {{ $insightWarning['bands'] }}.
                    Review them under <em>Admin &rarr; Risk Settings</em> before acting on the absolute
                    counts alone.
                </p>
            </div>
        </div>
    @endif
    <div class="row">
        <div class="col-xl-6 mb-4">
            <div class="card h-100">
                <div class="card-header">
                    <i class="fas fa-sliders-h text-primary me-2"></i> Risk Band Definitions
                </div>
                <div class="card-body">
                    <table class="table table-sm mb-0">
                        <thead>
                            <tr>
                                <th>Band</th>
                                <th class="text-end">Configured</th>
                                <th class="text-end">Effective</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(($insights['bands'] ?? []) as $level => $range)
                                <tr>
                                    <td>
                                        <span class="badge {{ $level === 'High' ? 'badge-risk-high' : ($level === 'Moderate' ? 'badge-risk-moderate' : 'badge-risk-low') }}">
                                            {{ $level }}
                                        </span>
                                    </td>
                                    <td class="text-end">{{ $range }}</td>
                                    <td class="text-end">{{ $insights['bands_effective'][$level] ?? $range }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <p class="small text-muted mb-0 mt-2">
                        The AI supplies the score; these bands assign the level deterministically, so the
                        same score always becomes the same band.
                    </p>
                </div>
            </div>
        </div>

        <div class="col-xl-6 mb-4">
            <div class="card h-100">
                <div class="card-header">
                    <i class="fas fa-ranking-star text-primary me-2"></i> Breakdown by Year Level
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-sm table-hover align-middle mb-0">
                            <thead>
                                <tr>
                                    <th>Year level</th>
                                    <th class="text-end">Monitored</th>
                                    <th class="text-end">High</th>
                                    <th class="text-end">High %</th>
                                    <th class="text-end">Moderate</th>
                                    <th class="text-end">Low</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse(($insights['year_levels'] ?? []) as $year)
                                    <tr>
                                        <td class="fw-semibold">{{ $year['label'] }}</td>
                                        <td class="text-end">{{ number_format((int) $year['monitored']) }}</td>
                                        <td class="text-end">
                                            <span class="badge badge-risk-high">{{ number_format((int) $year['counts']['High']) }}</span>
                                        </td>
                                        <td class="text-end">{{ number_format((float) $year['percentages']['High'], 2) }}%</td>
                                        <td class="text-end">{{ number_format((int) $year['counts']['Moderate']) }}</td>
                                        <td class="text-end">{{ number_format((int) $year['counts']['Low']) }}</td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="6" class="text-center text-muted py-3">No year-level data for this period.</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6 mb-4">
            <div class="card h-100">
                <div class="card-header">
                    <i class="fas fa-timeline text-primary me-2"></i> Term Progression
                    <span class="text-muted small ms-2">Prelim to Finals</span>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-sm table-hover align-middle mb-0">
                            <thead>
                                <tr>
                                    <th>Period</th>
                                    <th class="text-end">Monitored</th>
                                    <th class="text-end">High</th>
                                    <th class="text-end">High %</th>
                                    <th class="text-end">Escalations</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse(($insights['period_series'] ?? []) as $entry)
                                    <tr class="{{ ($snapshotMeta['grading_period'] ?? '') === $entry['period'] ? 'table-active' : '' }}">
                                        <td class="fw-semibold">{{ $entry['period'] }}</td>
                                        <td class="text-end">{{ number_format((int) $entry['monitored']) }}</td>
                                        <td class="text-end text-danger">{{ number_format((int) $entry['high']) }}</td>
                                        <td class="text-end">{{ number_format((float) $entry['high_percentage'], 2) }}%</td>
                                        <td class="text-end">{{ number_format((int) $entry['escalations']) }}</td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="5" class="text-center text-muted py-3">No period data for this term.</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-6 mb-4">
            <div class="card h-100">
                <div class="card-header">
                    <i class="fas fa-arrow-up-right-dots text-primary me-2"></i> Intervention Status
                    <span class="text-muted small ms-2">(escalation hand-off)</span>
                </div>
                <div class="card-body">
                    @if(!empty($intervention))
                        <table class="table table-sm mb-3">
                            <tbody>
                                <tr>
                                    <td>High-risk students in this period</td>
                                    <td class="text-end fw-bold">{{ number_format((int) $intervention['high_risk']) }}</td>
                                </tr>
                                <tr>
                                    <td>Escalated to a Guidance Counselor</td>
                                    <td class="text-end fw-bold text-success">{{ number_format((int) $intervention['high_escalated']) }}</td>
                                </tr>
                                <tr>
                                    <td>Still awaiting escalation</td>
                                    <td class="text-end fw-bold {{ (int) $intervention['high_pending'] > 0 ? 'text-danger' : 'text-success' }}">
                                        {{ number_format((int) $intervention['high_pending']) }}
                                    </td>
                                </tr>
                                <tr>
                                    <td>Escalation coverage of the High-risk group</td>
                                    <td class="text-end fw-bold">{{ number_format((float) $intervention['coverage_percentage'], 2) }}%</td>
                                </tr>
                                <tr>
                                    <td>Escalation records raised this period</td>
                                    <td class="text-end">{{ number_format((int) $intervention['total_escalations']) }}</td>
                                </tr>
                                <tr>
                                    <td>Open cases (not yet Resolved/Closed)</td>
                                    <td class="text-end">{{ number_format((int) $intervention['open_cases']) }}</td>
                                </tr>
                                <tr>
                                    <td>Resolved or closed cases</td>
                                    <td class="text-end">{{ number_format((int) $intervention['resolved_cases']) }}</td>
                                </tr>
                            </tbody>
                        </table>
                        @if(!empty($intervention['note']))
                            <div class="alert alert-warning small mb-0">
                                <i class="fas fa-circle-info me-1"></i>{{ $intervention['note'] }}
                            </div>
                        @endif
                    @else
                        <p class="text-muted mb-0">No intervention data available.</p>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endif


<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-fingerprint text-primary me-2"></i> Report Provenance &amp; Reproducibility
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-lg-7">
                <table class="table table-sm mb-0">
                    <tbody>
                        <tr>
                            <td>Computation method</td>
                            <td class="fw-bold">{{ $computation }}</td>
                        </tr>
                        <tr>
                            <td>Generative AI used</td>
                            <td>
                                @if($aiUsed)
                                    <span class="badge bg-danger">YES</span>
                                @else
                                    <span class="badge bg-success">NO</span>
                                @endif
                            </td>
                        </tr>
                        <tr>
                            <td>External service calls</td>
                            <td class="fw-bold">{{ number_format((int) ($snapshot['meta']['external_service_calls'] ?? 0)) }}</td>
                        </tr>
                        <tr>
                            <td>Source table</td>
                            <td>
                                <code>{{ $snapshot['meta']['source']['table'] ?? 'risk_scores' }}</code>
                                (status <code>{{ $snapshot['meta']['source']['processing_status'] ?? 'completed' }}</code>,
                                students <code>{{ $snapshot['meta']['source']['student_status'] ?? 'Active' }}</code>)
                            </td>
                        </tr>
                        <tr>
                            <td>Formula version</td>
                            <td class="fw-bold">v{{ $formulaVersion }}</td>
                        </tr>
                        <tr>
                            <td>Snapshot SHA-256</td>
                            <td><code class="text-break">{{ $digest }}</code></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-lg-5">
                <div class="alert alert-light border mb-0 h-100">
                    <p class="small mb-2">
                        <i class="fas fa-info-circle text-primary me-1"></i>
                        The risk <strong>scores</strong> come from the AI assessment engine; this report is
                        compiled by <strong>deterministic, rule-based aggregation</strong> of those stored
                        scores. No generative AI, language model or external service was invoked to produce
                        the document itself.
                    </p>
                    <p class="small mb-0">
                        Because every figure is derived from the stored snapshot, re-running the same aggregation
                        over the same data produces the <strong>identical</strong> document and digest — which is
                        what makes the downloaded PDF independently verifiable.
                    </p>
                </div>
            </div>
        </div>

        @if($canManage ?? false)
            <hr>
            <div class="d-flex flex-wrap gap-2 align-items-center">
                <form method="POST" action="{{ $shareRoute }}" class="d-flex flex-wrap gap-2 align-items-center">
                    @csrf
                    <input type="hidden" name="share" value="{{ $report->is_shared ? 0 : 1 }}">
                    @if(!$report->is_shared)
                        <input type="hidden" name="roles[]" value="admin">
                        <input type="hidden" name="roles[]" value="counselor">
                    @endif
                    <span class="small text-muted me-2">
                        @if($report->is_shared)
                            Shared with {{ count($sharedRoles) ? implode(' and ', $sharedRoles) : 'no roles' }}@if($report->shared_at) on {{ $report->shared_at }}@endif
                        @else
                            This report is private to your department.
                        @endif
                    </span>
                    <button type="submit" class="btn btn-sm {{ $report->is_shared ? 'btn-outline-secondary' : 'btn-success' }}">
                        @if($report->is_shared)
                            <i class="fas fa-lock me-1"></i> Revoke Sharing
                        @else
                            <i class="fas fa-share-alt me-1"></i> Share with Admin &amp; Counselors
                        @endif
                    </button>
                </form>

                <form method="POST" action="{{ route('academic-head.reports.destroy', $report->id) }}"
                      onsubmit="return confirm('Delete this stored report? The snapshot cannot be recovered.');">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-sm btn-outline-danger">
                        <i class="fas fa-trash me-1"></i> Delete
                    </button>
                </form>
            </div>
        @endif
    </div>
</div>
@endsection

@push('scripts')
<script>
(function () {
    var canvas = document.getElementById('eotDistributionChart');
    if (!canvas || typeof Chart === 'undefined') { return; }

    var chart = JSON.parse(canvas.getAttribute('data-chart') || '{}');
    var datasets = [{
        label: @json($snapshotMeta['grading_period'] ?? 'Current'),
        data: chart.current || [],
        backgroundColor: ['#dc3545', '#ffc107', '#28a745'],
        borderWidth: 1,
        borderColor: '#fff'
    }];

    // Only plot the comparison series when a previous period actually exists.
    if (chart.previousPeriod) {
        datasets.push({
            label: chart.previousPeriod,
            data: chart.previous || [],
            backgroundColor: ['rgba(220,53,69,0.35)', 'rgba(255,193,7,0.35)', 'rgba(40,167,69,0.35)'],
            borderWidth: 1,
            borderColor: '#fff'
        });
    }

    new Chart(canvas.getContext('2d'), {
        type: 'bar',
        data: { labels: chart.labels || ['High', 'Moderate', 'Low'], datasets: datasets },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { position: 'bottom' },
                tooltip: {
                    callbacks: {
                        label: function (context) {
                            return context.dataset.label + ': ' + context.parsed.y + ' students';
                        }
                    }
                }
            },
            scales: {
                y: { beginAtZero: true, ticks: { precision: 0 } },
                x: { grid: { display: false } }
            }
        }
    });

    @if(!empty($verifyRoute))
    var verifyBtn = document.getElementById('verifyBtn');
    if (verifyBtn) {
        verifyBtn.addEventListener('click', function () {
            var original = verifyBtn.innerHTML;
            verifyBtn.disabled = true;
            verifyBtn.innerHTML = '<span class="spinner-border spinner-border-sm me-1"></span> Verifying...';

            fetch(@json($verifyRoute), { headers: { 'Accept': 'application/json' } })
                .then(function (response) { return response.json(); })
                .then(function (data) {
                    verifyBtn.disabled = false;
                    verifyBtn.innerHTML = original;

                    if (!data.success) {
                        alert('Verification failed: ' + (data.message || 'unknown error'));
                        return;
                    }

                    alert([
                        'Stored digest:     ' + data.stored_digest,
                        'Recomputed digest: ' + data.recomputed_digest,
                        '',
                        'Snapshot matches its digest: ' + (data.payload_digest_matches ? 'YES' : 'NO'),
                        'Re-aggregation reproduces it: ' + (data.matches ? 'YES' : 'NO - underlying data has changed since generation'),
                        '',
                        'Generative AI used: ' + (data.ai_used ? 'YES' : 'NO'),
                        'External service calls: ' + data.external_service_calls,
                        'Computation: ' + data.computation + ' (formula v' + data.formula_version + ')'
                    ].join('\n'));
                })
                .catch(function (error) {
                    verifyBtn.disabled = false;
                    verifyBtn.innerHTML = original;
                    alert('Verification request failed: ' + error);
                });
        });
    }
    @endif
})();
</script>
@endpush
