<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    protected array $enumTables = [
        'grades',
        'attendance_summaries',
        'risk_scores',
        'flags',
        'risk_overrides',
        'escalations',
        'academic_calendar',
    ];

    protected array $stringTables = [
        'intervention_recommendations',
        'risk_score_cache',
    ];

    /** The canonical three-period whitelist. */
    protected array $periods = ['Prelim', 'Midterm', 'Finals'];

    public function up(): void
    {
        // 1. Purge every row belonging to the deprecated period.
        foreach (array_merge($this->enumTables, $this->stringTables) as $table) {
            if (!Schema::hasTable($table) || !Schema::hasColumn($table, 'grading_period')) {
                continue;
            }

            DB::table($table)->where('grading_period', 'Semifinal')->delete();
        }

        if (Schema::hasTable('academic_calendar')) {
            DB::table('academic_calendar')
                ->where('grading_period', 'Finals')
                ->where('period_number', '>', count($this->periods))
                ->update(['period_number' => count($this->periods)]);
        }

        // 3. Narrow the ENUM definition on every enum-backed table.
        foreach ($this->enumTables as $table) {
            if (!Schema::hasTable($table) || !Schema::hasColumn($table, 'grading_period')) {
                continue;
            }

            Schema::table($table, function (Blueprint $blueprint) {
                $blueprint->enum('grading_period', $this->periods)->change();
            });
        }
    }

    public function down(): void
    {
        // Restore the ENUM definitions (data restore is not attempted — the
        // purged rows are regenerated by the seeders).
        foreach ($this->enumTables as $table) {
            if (!Schema::hasTable($table) || !Schema::hasColumn($table, 'grading_period')) {
                continue;
            }

            Schema::table($table, function (Blueprint $blueprint) {
                $blueprint->enum('grading_period', ['Prelim', 'Midterm', 'Semifinal', 'Finals'])->change();
            });
        }

        if (Schema::hasTable('academic_calendar')) {
            DB::table('academic_calendar')
                ->where('grading_period', 'Finals')
                ->update(['period_number' => 4]);
        }
    }
};
