<div class="table-responsive">
    <table class="table table-hover align-middle">
        <thead>
            <tr>
                <th>Department</th>
                <th>Period</th>
                <th>School Year</th>
                <th class="text-end">Monitored</th>
                <th class="text-end">High</th>
                <th class="text-end">Moderate</th>
                <th class="text-end">Low</th>
                <th class="text-end">High %</th>
                <th>Comparison</th>
                <th>Generated By</th>
                <th class="text-end">Actions</th>
            </tr>
        </thead>
        <tbody>
            @forelse($reports as $report)
                <tr>
                    <td>
                        <span class="fw-bold">{{ $report->department_code ?? 'N/A' }}</span>
                        <div class="small text-muted">{{ $report->department_name ?? '' }}</div>
                    </td>
                    <td><span class="badge bg-primary">{{ $report->grading_period }}</span></td>
                    <td>{{ $report->school_year }}</td>
                    <td class="text-end fw-bold">{{ number_format((int) $report->total_monitored) }}</td>
                    <td class="text-end text-danger">{{ number_format((int) $report->high_count) }}</td>
                    <td class="text-end text-warning">{{ number_format((int) $report->moderate_count) }}</td>
                    <td class="text-end text-success">{{ number_format((int) $report->low_count) }}</td>
                    <td class="text-end">{{ number_format((float) $report->high_percentage, 2) }}%</td>
                    <td>
                        <span class="small text-muted">
                            {{ $report->previous_grading_period ? 'vs ' . $report->previous_grading_period : 'baseline' }}
                        </span>
                    </td>
                    <td>
                        <div class="small">{{ $report->generated_by_name ?? 'Unknown' }}</div>
                        <div class="small text-muted">{{ $report->generated_at }}</div>
                    </td>
                    <td class="text-end">
                        <div class="btn-group btn-group-sm">
                            <a href="{{ route('admin.reports.preview', $report->id) }}"
                               class="btn btn-outline-primary" title="View report">
                                <i class="fas fa-eye"></i>
                            </a>
                            <a href="{{ route('admin.reports.pdf', $report->id) }}"
                               class="btn btn-outline-danger" title="Download PDF">
                                <i class="fas fa-file-pdf"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="11" class="text-center text-muted py-4">
                        <i class="fas fa-inbox fa-2x d-block mb-2"></i>
                        No end-of-term reports have been shared with administrators yet.
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>
</div>